name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call-common-ci:
    uses: its-the-vibe/.github/.github/workflows/common-ci.yaml@main
    permissions:
      contents: read
      packages: write
    secrets: inherit
